version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: crypto
    restart: on-failure
    ports:
      - 5434:5432
    networks:
      - internal
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  internal:
    driver: bridge